spring:
  datasource:
    url: jdbc:mysql://localhost:3306/biz_english?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: bizuser
    password: bizpass123!
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: Asia/Seoul
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
logging:
  level:
    org.flywaydb: info
    org.hibernate.SQL: debug
